import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Layout from "../../components/Layout";
import {useRouter} from "next/router";
import { Button} from "@mui/material";
import {DataSaverOn} from "@mui/icons-material";
import DigimonsList from "../../components/DigimonsList";
import React from "react";


export default function verDigimons() {
    const router = useRouter();

    const handleClik = async (idElegido: any) => {
        await router.push('/formularios/nuevoDigimon/' + idElegido);
    }

    return (
        <Layout>
            <Head>
                <title>Lista Digimons</title>
                <meta name="lista-digimons" content="Generated by create next app"/>
                <link rel="icon" href="/Logo.png"/>
            </Head>
            <h1 className={styles.tituloLista}>Lista de Digimons</h1>
            <div style={{textAlign: 'right', marginBottom: '2.5em'}}>
                <Button variant="outlined"
                        startIcon={<DataSaverOn fontSize={"large"}/>}
                        onClick={() => handleClik(router.query.id)}
                >
                    Agregar Digimon
                </Button>
            </div>
            <div>
                <DigimonsList/>
            </div>
        </Layout>
    )
}