import {useRouter} from "next/router";
import {ChangeEvent, FormEvent, useState} from "react";
import Layout from "../../../components/Layout";
import {Button, Card, CardContent, Grid, TextField, Typography} from "@mui/material";
import {Save} from "@mui/icons-material";
import * as React from "react";
import Head from "next/head";
import {Digimon} from "../../../interfaces/digimon";

export default function id() {
    const router = useRouter();

    const [digimon, setDigimon] = useState({
        iddigimon: '',
        idelegido: '',
        nombre: '',
        nivel: '',
        atributo: '',
        tipo: '',
        imagen: ''
    });

    const handleSubmit = async (idElegido:any, e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        await createDigimon(router.query.id,digimon);
        await router.push('../../digimons/'+idElegido);
    }

    const createDigimon = async (idElegido: any, digimon: Digimon) => {
        await fetch('http://localhost:3000/api/digi/'+idElegido, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(digimon)
        })
    }

    const handleChange = ({target: {name, value}}: ChangeEvent<HTMLInputElement>) => {
        setDigimon ({...digimon, [name]: value});
    }

    return (
        <Layout>
            <Head>
                <title>Nuevo Digimon</title>
                <meta name="nuevo-digimon" content="Generated by create next app"/>
                <link rel="icon" href="/Logo.png"/>
            </Head>
            <Grid container justifyContent={'center'}>
                <Card
                    sx={{mt: 5}}
                    style={{padding: '1rem'}}
                >
                    <Typography variant={'h5'} textAlign={'center'} fontWeight={'bolder'}>
                        Formulario Nuevo Digimon
                    </Typography>
                    <CardContent>
                        <form onSubmit={(e)=>handleSubmit(router.query.id,e)}>
                            <TextField variant={'outlined'} label={"Ingresa el ID Digimon"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       fullWidth={true}
                                       name={"iddigimon"}
                                       onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el ID Elegido"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"idelegido"}
                                       fullWidth={true}
                                       value={''+router.query.id}
                                       onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Nombre"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"nombre"}
                                       fullWidth={true}
                                      onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Nivel"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"nivel"}
                                       fullWidth={true}
                                      onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Atributo"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"atributo"}
                                       fullWidth={true}
                                       onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Tipo"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"tipo"}
                                       fullWidth={true}
                                       onChange={handleChange}
                            />
                            <TextField variant={'outlined'} label={"Ingresa una url"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"imagen"}
                                       fullWidth={true}
                                       onChange={handleChange}
                            />
                            <div style={{marginTop:'1rem', textAlign: 'center'}}>
                                <Button type={'submit'} variant="outlined" color={"primary"} startIcon={<Save/>}>
                                    Guardar
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </Grid>
        </Layout>
    )
}