import * as React from 'react';
import {useRouter} from "next/router";
import {ChangeEvent, FormEvent, useState} from "react";
import Layout from "../../../components/Layout";
import {Button, Card, CardContent, Grid, TextField, Typography} from "@mui/material";
import {Cached, Save} from "@mui/icons-material";
import Head from "next/head";
import {useEffect} from "react";
import {Digimon} from "../../../interfaces/digimon";

export default function editDigimon() {
    const router = useRouter();

    const [digimon, setDigimon] = useState({
        iddigimon: '',
        idelegido: '',
        nombre: '',
        nivel: '',
        atributo: '',
        tipo: '',
        imagen: ''
    });

    const loadDigimon = async (id: string) => {
        const res = await fetch('http://localhost:3000/api/update/' + id);
        const digimonBE = await res.json();
        console.log(digimonBE);
        setDigimon(digimonBE);
    }

    useEffect(() => {
        if (typeof router.query.id === 'string') {
            loadDigimon(router.query.id)
        }
    }, [router.query])

    const handleChange = ({target: {name, value}}: ChangeEvent<HTMLInputElement>) => {
        setDigimon({...digimon, [name]: value});
    }

    const handleSubmit = async (idDigimon: any, e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        await updateDigimon(router.query.id, digimon);
        await router.push('../../digimons/' + idDigimon);
    }

    const updateDigimon = async (idDigimon: any, digimon: Digimon) => {
        await fetch('http://localhost:3000/api/digi/' + idDigimon, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(digimon)
        })
    }

    return (
        <Layout>
            <Head>
                <title>Editar Digimon</title>
                <meta name="editar-digimon" content="Generated by create next app"/>
                <link rel="icon" href="/Logo.png"/>
            </Head>
            {/*<h1>nombre {digimon.nombre}</h1>*/}
            <Grid container justifyContent={'center'}>
                <Card
                    sx={{mt: 5}}
                    style={{padding: '1rem'}}
                >
                    <Typography variant={'h5'} textAlign={'center'} fontWeight={'bolder'}>
                        Editar Digimon
                    </Typography>
                    <CardContent>
                        <form onSubmit={(e) => handleSubmit(digimon.idelegido, e)}>
                            <TextField variant={'outlined'} label={"Ingresa el ID Digimon"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       fullWidth={true}
                                       name={"iddigimon"}
                                       onChange={handleChange}
                                       value={digimon.iddigimon}
                                       disabled={true}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el ID Elegido"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"idelegido"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.idelegido}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Nombre"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"nombre"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.nombre}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Nivel"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"nivel"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.nivel}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Atributo"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"atributo"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.atributo}
                            />
                            <TextField variant={'outlined'} label={"Ingresa el Tipo"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"tipo"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.tipo}
                            />
                            <TextField variant={'outlined'} label={"Ingresa una url"}
                                       sx={{display: 'block', margin: '.5rem .0 1rem 0'}}
                                       name={"imagen"}
                                       fullWidth={true}
                                       onChange={handleChange}
                                       value={digimon.imagen}
                            />
                            <div style={{marginTop: '1rem', textAlign: 'center'}}>
                                <Button type={'submit'} variant="outlined" color={"primary"} startIcon={<Cached/>}>
                                    Actualizar
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </Grid>
        </Layout>
    )
}