import {Elegido} from "../interfaces/elegido";
import {Grid, Button} from "@mui/material";
import styled from "@emotion/styled";
import {AddBox} from "@mui/icons-material";
import {useRouter} from "next/router";
import ElegidosList from "../components/ElegidosList";
import React from "react";
import Head from "next/head";


const ImagenPrincipal = styled.img`
  width: 250px;
  height: 120px;
  margin: 35px;
  border-radius: 25px;
`;

export default function Elegidos(props: Elegido) {

    const router = useRouter();

    return (
        <>
            {
                props.idelegido?.length === 0 ? (
                    <Grid>
                        <Button>Base de datos vacia</Button>
                    </Grid>
                ) : (
                    <div style={{width:'85%',justifyContent: 'center',margin:'auto'}}>
                        <Head>
                            <title>Lista Elegidos</title>
                            <meta name="lista-elegidos" content="Generated by create next app"/>
                            <link rel="icon" href="/Logo.png"/>
                        </Head>
                        <div style={{textAlign: "center"}}>
                            <ImagenPrincipal
                                src={'/Logo.png'}
                                title={"Intro Id"}/>
                        </div>
                        <div style={{textAlign: 'right', marginRight:'1rem'}}>
                            <Button onClick={() => router.push('/formularios/nuevoElegido')} variant="outlined"
                                    startIcon={<AddBox fontSize={"large"}/>}>
                                Agregar Elegido
                            </Button>
                        </div>
                        <div>
                            <ElegidosList></ElegidosList>
                        </div>
                    </div>


                )
            }
        </>
    )
}
