import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from "@emotion/styled";

const ImagenPrincipal = styled.img`
  width: 600px;
  height: 400px;
  margin: 35px;
  border-radius: 25px;
`;

const BotonInicio = styled.button`
  background-color: #86B8E2;
  border-radius: 100px;
  box-shadow: rgba(226,135,67, .2) 0 -25px 18px -14px inset,
  rgba(226,135,67, .15) 0 1px 2px,
  rgba(226,135,67, .15) 0 2px 4px,
  rgba(226,135,67, .15) 0 4px 8px,
  rgba(226,135,67, .15) 0 8px 16px,
  rgba(226,135,67, .15) 0 16px 32px;
  color: darkblue;
  cursor: pointer;
  display: inline-block;
  font-family: DigivolveNormal;
  padding: 7px 20px;
  text-align: center;
  text-decoration: none;
  transition: all 250ms;
  border: 0;
  font-size: 40px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  margin: 50px;
`;

const Home = () => {
  return (
      <div className={styles.container}>
        <Head>
          <title>DIGIMON APP</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/Logo.png"/>
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Bienvenido a Digimon APP
          </h1>
          <ImagenPrincipal
              src={"https://media3.giphy.com/media/11TkuRl1Ff32ak/giphy.gif?cid=790b76114f1863dc1e1bcd7bd724f3e768730cafbd6709b7&rid=giphy.gif&ct=g"}
              title={"Intro Id"}
          />
          <a href={"/elegidos"}>
            <BotonInicio>Ingresar</BotonInicio>
          </a>
        </main>
      </div>
  )
}

export default Home